- id: b4186bd84bca47a3ad0ccf423c87297b
  alias: Daily Backup at 3am
  trigger:
  - at: 03:01:00
    platform: time
  action:
  - data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
    service: hassio.snapshot_full
  - data:
      message: Hass.io Snapshot Created
      target:
      - channel/lunzhome
    data_template:
      message: Creating backup named "Automated Backup {{ now().strftime('%Y-%m-%d')
        }}"
    service: notify.pushbullet
- id: '1522393589366'
  alias: Upload Snapshot to Dropbox at 3am
  trigger:
  - at: 03:30:00
    platform: time
  condition:
  - condition: state
    entity_id: automation.upload_snapshot_to_dropbox_at_3am
    state: 'on'
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
  - data:
      message: Hass.io Snapshot Uploaded to Dropbox
      target:
      - channel/lunzhome
    service: notify.pushbullet
- id: '1526803342640'
  alias: Copy to USB Drive at 3:15am
  trigger:
  - at: 03:15:00
    platform: time
  condition:
  - condition: state
    entity_id: automation.copy_to_usb_drive_at_315am
    state: 'on'
  action:
  - data:
      addon: local_copy_backups_to_sda1
    service: hassio.addon_start
  - data:
      message: Hass.io Snapshots copied to USB Drive
      target:
      - channel/lunzhome
    service: notify.pushbullet
