- id: '1522393589366'
  alias: Upload Snapshot to Dropbox at 5am
  trigger:
  - at: 05:00:00
    platform: time
  condition:
  - condition: state
    entity_id: automation.upload_snapshot_to_dropbox_at_5am
    state: 'on'
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
  - data:
      message: Hass.io Snapshot Uploaded to Dropbox
      target:
      - channel/lunzhome
    service: notify.pushbullet
- id: '1526803342640'
  alias: Copy to USB Drive at 4am
  trigger:
  - at: 04:00:00
    platform: time
  condition:
  - condition: state
    entity_id: automation.copy_to_usb_drive_at_400am
    state: 'on'
  action:
  - data:
      addon: local_copy_backups_to_sda1
    service: hassio.addon_start
  - data:
      message: Hass.io Snapshots copied to USB Drive
      target:
      - channel/lunzhome
    service: notify.pushbullet
- id: '1529482399644'
  alias: Day/Night Theme
  trigger:
  - event: start
    platform: homeassistant
  - entity_id: sun.sun
    from: above_horizon
    platform: state
    to: below_horizon
  condition: []
  action:
  - data:
      name: dark_mint
    service: frontend.set_theme
- id: '1543992499281'
  alias: SFTP Daily Backup at 4am
  trigger:
  - at: '4:00:00'
    platform: time
  condition: []
  action:
  - data:
      addon: ce20243c_remote_backup
    service: hassio.addon_start
- id: '1550625961430'
  alias: Upload Snapshot to Google Drive at 430am
  trigger:
  - at: 04:30:00
    platform: time
  condition:
  - condition: state
    entity_id: automation.upload_snapshot_to_google_drive_at_430am
    state: 'on'
  action:
  - service: rest_command.google_backup
  - data: {}
    service: notify.ios_lunziphone_ios
  - data:
      message: Hass.io Snapshot Uploaded to Google Drive
      target:
      - channel/lunzhome
    service: notify.pushbullet
- id: '1560795323262'
  alias: Daily Backup at 3am
  trigger:
  - at: 03:01:00
    platform: time
  condition: []
  action:
  - data:
      addons:
      - a0d7b954_influxdb
      - core_mariadb
      - b794684e_configurator_latest
      - a0d7b954_pi-hole
      - 40817795_nginxproxymanager
      - a0d7b954_sonweb
      - a0d7b954_grafana
      - core_duckdns
      - a0d7b954_ssh
      - a0d7b954_adb
      - ce20243c_remote_backup
      - cebe7a76_hassio_google_drive_backup
      - a0d7b954_zerotier
      - a0d7b954_mqtt
      - a0d7b954_ftp
      - a0d7b954_logviewer
      - a0d7b954_glances
      - a0d7b954_sqlite-web
      - 6e66619d_room-assistant
      - a0d7b954_home-panel
      - local_room-assistant
      - 03d23610_dasshio
      - core_git_pull
      - 7be23ff5_dropbox_sync
      - core_rpc_shutdown
      - a0d7b954_appdaemon3
      - a722577e_apcupsd
      - a0d7b954_spotify
      - a0d7b954_aircast
      - f190cc33_firetv-server
      - fe41fc28_caddy
      - e5829d31_devlocator
      - a0d7b954_jupyterlablite
      - a0d7b954_motioneye
      - a0d7b954_nodered
      - 3833edd4_googlebackup
      - core_check_config
      - core_samba
      folders:
      - homeassistant
      - share
      - ssl
      name: Automated Partial Backup
    service: hassio.snapshot_partial
  - data:
      message: Creating backup named Automated Backup {{ now().strftime('%Y-%m-%d')}}
      target:
      - channel/lunzhome
    service: notify.pushbullet
- id: '1561585571378'
  alias: Update Notification
  trigger:
  - entity_id: binary_sensor.updater
    from: '''off'''
    platform: state
    to: '''on'''
  condition: []
  action:
  - data:
      data_template:
        message: Home Assistant  {{ state_attr('binary_sensor.updater', 'newest_version')
          }}  is now available.
        target: channel/LunzHome
        title: New Home Assistant Release
    service: notify.pushbullet
- id: '1569409841150'
  alias: iOS_Toggle_Fan
  trigger:
  - event_data:
      actionName: Fan_Toggle
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.sonoff_amplifier
    service: switch.toggle
- id: '1569410375070'
  alias: iOS_Michael_Lights_Toggle
  trigger:
  - event_data:
      actionName: Michael_Lights_Toggle
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data:
      entity_id: group.lights_michael2
    service: switch.toggle
- id: '1571872974980'
  alias: Zerver Low Disk Space
  trigger:
  - above: '90'
    entity_id: sensor.disk_use_percent_home
    platform: numeric_state
  condition:
  - after: sunrise
    after_offset: '2'
    condition: sun
  action:
  - service: notify.mobile_app_lunziphone11
    data:
      title: Out of Space!
      message: Oh wow, you are out of space on Home Assistant!
  mode: single
- id: '1579081800469'
  alias: Turn off bright lights at 09:30pm
  description: ''
  trigger:
  - at: '21:30:00'
    platform: time
  condition: []
  action:
  - condition: state
    entity_id: switch.sonoff_basic01_relay
    state: 'off'
  - condition: state
    entity_id: switch.sonoff_basic02_relay
    state: 'off'
- id: '1584426003321'
  alias: Dishwasher - Send Alert When Clean
  description: ''
  trigger:
  - entity_id: input_select.dishwasher_status
    platform: state
    to: Clean
  condition:
  - after: 08:29:00
    before: '22:30:00'
    condition: time
  - condition: and
    conditions:
    - condition: state
      entity_id: group.roommates
      state: home
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clear
  action:
  - data:
      message: Dishwasher is Clean
    service: notify.mobile_app_lunziphone11
  - data:
      message: Dishwasher is Clean!
      target:
      - channel/lunzhome
    service: notify.pushbullet
- id: '1588181685264'
  alias: iOS_Michael_Lights_Off
  description: ''
  trigger:
  - event_data:
      actionName: Michael_Lights_Off
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: group.lights_michael2
    service: switch.turn_off
- id: '1588182302527'
  alias: iOS_Michael_Lights_On
  description: ''
  trigger:
  - event_data:
      actionName: Michael_Lights_On
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: group.lights_michael2
    service: switch.turn_on
- id: '1583913595577'
  alias: Hugo Remote CF4AFC Button 1 - Turn Everything On
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf4afc
    platform: state
    to: '1'
  condition: []
  action:
  - entity_id: group.lights_michael2
    service: homeassistant.turn_on
- id: '1587769458708'
  alias: Hugo Remote CF4AFC Button 2 - Toggle Fluorescent Lights
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf4afc
    platform: state
    to: '2'
  condition: []
  action:
  - entity_id: switch.kmc01_relay_1
    service: homeassistant.toggle
  mode: single
- id: '1587769458103'
  alias: Hugo Remote CF4AFC Button 3 - Toggle Chess Lamp
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf4afc
    platform: state
    to: '3'
  condition: []
  action:
  - entity_id: switch.sonoff_basic02_relay
    service: homeassistant.toggle
- id: '1583913339883'
  alias: Hugo Remote CF4AFC Button 4 - Turn Everything Off
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf4afc
    platform: state
    to: '4'
  condition:
  - condition: state
    entity_id: group.lights_michael2
    state: 'on'
  action:
  - entity_id: group.lights_michael2
    service: homeassistant.turn_off
- id: '1583913595578'
  alias: Hugo Remote CF41A4 Button 1 - Turn Everything On
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf41a4
    platform: state
    to: '1'
  condition: []
  action:
  - entity_id: group.lights_michael2
    service: homeassistant.turn_on
- id: '1587769458709'
  alias: Hugo Remote CF41A4 Button 2 - Toggle Fluorescent Lights
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf41a4
    platform: state
    to: '2'
  condition: []
  action:
  - entity_id: switch.kmc01_relay_1
    service: homeassistant.toggle
  mode: single
- id: '1587769458101'
  alias: Hugo Remote CF41A4 Button 3 - Toggle Chess Lamp
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf41a4
    platform: state
    to: '3'
  condition: []
  action:
  - entity_id: switch.sonoff_basic02_relay
    service: homeassistant.toggle
  - service: homeassistant.toggle
    data: {}
    entity_id: switch.kmc01_relay_3
  mode: single
- id: '1583913339884'
  alias: Hugo Remote CF41A4 Button 4 - Turn Everything Off
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf41a4
    platform: state
    to: '4'
  condition:
  - condition: state
    entity_id: group.lights_michael2
    state: 'on'
  action:
  - entity_id: group.lights_michael2
    service: homeassistant.turn_off
- id: '1583913595579'
  alias: Hugo Remote CF3AB8 Button 1 - Turn Everything On
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf4ab8
    platform: state
    to: '1'
  condition: []
  action:
  - entity_id: group.lights_michael2
    service: homeassistant.turn_on
- id: '1587769458700'
  alias: Hugo Remote CF3AB8 Button 2 - Toggle Fluorescent Lights
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf4ab8
    platform: state
    to: '2'
  condition: []
  action:
  - entity_id: switch.sonoff_basic01_relay
    service: homeassistant.toggle
- id: '1587769458100'
  alias: Hugo Remote CF3AB8 Button 3 - Toggle Chess Lamp
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf4ab8
    platform: state
    to: '3'
  condition: []
  action:
  - entity_id: switch.sonoff_basic02_relay
    service: homeassistant.toggle
- id: '1583913339885'
  alias: Hugo Remote CF3AB8 Button 4 - Turn Everything Off
  description: ''
  trigger:
  - entity_id: sensor.hugo_cf4ab8
    platform: state
    to: '4'
  condition:
  - condition: state
    entity_id: group.lights_michael2
    state: 'on'
  action:
  - entity_id: group.lights_michael2
    service: homeassistant.turn_off
- id: '1603308289689'
  alias: Twilio Mac Microphone Status Light - On
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.mlunzer_twilio_mac_lunzpodz
  condition: []
  action:
  - type: turn_on
    device_id: af8d2dbaf5174136b70cd9c5cc5c1b6d
    entity_id: light.sn1_light
    domain: light
    brightness_pct: 100
  mode: single
- id: '1603308763473'
  alias: Twilio Mac Microphone Status Light - Off
  description: ''
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    entity_id: binary_sensor.mlunzer_twilio_mac_lunzpodz
  condition: []
  action:
  - type: turn_off
    device_id: af8d2dbaf5174136b70cd9c5cc5c1b6d
    entity_id: light.sn1_light
    domain: light
  mode: single
- id: '1603772607768'
  alias: Handrail Christmas Lights Automation
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - condition: state
    entity_id: switch.sonoff_basic01_relay
    state: 'on'
  mode: single
- id: '1621920723607'
  alias: Garbage Reminder
  description: ''
  use_blueprint:
    path: westenberg/garbage-reminder.yaml
    input:
      reminder_title: Garbage Reminder
      notifier: notify.notify
      garbage_sensor_1: sensor.garbage_collection
      reminder_time: '18:45:00'
      garbage_sensor_2: sensor.10_lunz_hdd_label_c
      garbage_sensor_3: sensor.10_lunz_hdd_free_space_c
      garbage_sensor_4: sensor.10_lunz_hdd_total_free_space_e
      reminder_message: The garbage will be picked up tomorrow!
      day_offset: '1'
