homekit:
  auto_start: False
  filter: 
    include_domains:
      - light
      - media_player

automation:
  - alias: 'Start HomeKit'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:05  # Waits 5 minutes
      - service: homekit.start