homeassistant:
  customize:

    sensor.pihole_ads_percentage_blocked_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent

    sensor.pihole_domains_blocked:
      friendly_name: Total Domains Blocked
      icon: mdi:do-not-disturb

    sensor.pihole_dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text

    sensor.pihole_dns_unique_domains:
      friendly_name: Unique Domains
      icon: mdi:approval


sensor:
  - platform: pi_hole
    host: localhost:4865
    monitored_conditions:
      - ads_percentage_today
      - ads_blocked_today
      - queries_cached
      - queries_forwarded
      - unique_domains
      - dns_queries_today
      - domains_being_blocked
      - unique_clients
      - clients_ever_seen

# Pi-Hole switch
# switch:
#   - platform: command_line
#     switches:
#       pihole_switch:
#         command_on: "curl -X GET 'http://192.168.1.2:4865/admin/api.php?enable&auth='"
#         command_off: "curl -X GET 'http://192.168.1.2:4865/admin/api.php?disable=3600&auth='"
#         command_state: "curl -X GET 'http://192.168.1.2:4865/admin/api.php?status'"
#         value_template: "{{ value_json.status == 'enabled' }}"


# moved back from /config/groups/pihole.yaml
group:
  Pi Hole:
    name: "Pi Hole"
    icon: mdi:alert-octagon
    entities:
      - switch.pihole_switch
      - sensor.pihole_dns_queries_today
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_today
      - sensor.pihole_domains_blocked
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_unique_domains
      - sensor.pihole_dns_unique_clients
      - sensor.pihole_dns_queries_cached
      - sensor.pihole_queries_cached
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_unique_clients
      - sensor.pihole_seen_clients
      - sensor.pihole_clients_ever_seen