homeassistant:
  customize:

    sensor.pihole_ads_percentage_blocked_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent

    sensor.pihole_domains_blocked:
      friendly_name: Total Domains Blocked
      icon: mdi:do-not-disturb

    sensor.pihole_dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text

    sensor.pihole_dns_unique_domains:
      friendly_name: Unique Domains
      icon: mdi:approval


sensor:
  - platform: pi_hole
    host: 192.168.1.17
    monitored_conditions:
      - ads_percentage_today
      - unique_domains
      - dns_queries_today
      - domains_being_blocked

# Pi-Hole switch
switch:
  - platform: command_line
    switches:
      pihole_switch:
        command_on: "curl -X GET 'http://192.168.1.17/admin/api.php?enable&auth='"
        command_off: "curl -X GET 'http://192.168.1.17/admin/api.php?disable=3600&auth='"
        command_state: "curl -X GET 'http://192.168.1.17/admin/api.php?status'"
        value_template: "{{ value_json.status == 'enabled' }}"

group:
  Pi Hole:
    entities:
      - switch.pihole_switch
      - sensor.pihole_dns_queries_today
      - sensor.pihole_domains_blocked
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_unique_domains